### ISSUE TITLE
There is no tags with version so main firmware can not be build

### ISSUE THREAD

**Issue by phush0** [mongoose-os-libs/wifi#1]
there is no tags currently, so mos build will return 
`Error: failed to git checkout 1.10: error: pathspec '1.10' did not match any file(s) known to git.`

**Comment by dimonomid** [comment]
Thanks for reporting.
So the underlying problem is that released mos (version 1.10 in your case) keeps using latest app sources; currently it uses `wifi` lib which didn't exist when 1.10 was cut.
We'll surely handle this underlying problem, but as a quick fix for now, 1.11 was cut. Please update your mos, and it will work.
